/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "stm32f411xe.h"

#include "tim.h"
#include "gpio.h"
#include "uart.h"

int countdown = 0;

void init_all(void)
{
	tim2_init();
	tim5_init();
	led_init();
	button_init();
	uart_init();

}

void print_reaction_time(uint32_t ms) {

	char msg[50];

	memset(msg, 0, sizeof(msg));
	snprintf(msg, sizeof(msg), "< Reaction Time : %ld ms >\r\n", ms);

	uart_write_str(msg);

}

void reset_stopwatch(void) {

	led_off();
	countdown = 0;

	tim2_stop();
	tim5_stop();

	tim2_reset();
	tim5_reset();
}

int main(void)
{
	init_all();
	led_off();

	tim2_start();

	while(1) {

		if ((TIM2->SR & TIM_SR_UIF) && !countdown) {
			TIM2->SR &= ~TIM_SR_UIF;
			uart_write_str("< Start!!! >\r\n");
			led_on();
			tim5_start();
			countdown = 1;
		}

		if (button_pressed()) {
			if (countdown) {
				uint32_t reaction_time = get_tim5_ms();
				print_reaction_time(reaction_time);

			} else {
				uart_write_str("< False Start! >\r\n");
			}

			reset_stopwatch();
			tim2_start();
		}

	}

}
