/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "systick.h"
#include "gpio.h"

enum frequencies {one, two, four};
int counter = 0;

void change_freq(void)
{
	switch (counter++ % 3)
	{
		case one:
			delay_ms(250); // 1 Hz to 2 Hz
			break;
		case two:
			delay_ms(125); // 2 Hz to 4 Hz
			break;
		case four:
			delay_ms(500); // 4 Hz to 1 Hz
			break;
		default:
			delay_ms(500);
	}

}

// detect transition from high to low (edge detection)
static int button_pressed() {

	static int prev_state = 0; // button is active low
	int curr_state = button_state(); // Returns 1 for released, 0 for pressed
	int pressed = 0;

	if (prev_state == 1 && curr_state == 0)
	{
		for(volatile int i = 0; i < 64000; i++);

		if (button_state() == 0)
			pressed = 1;
	}
	prev_state = curr_state;
	return pressed;

}

int main(void)
{
	gpio_en();
	systick_en();

	while(1)
	{
		// change Hz when button pressed
		if (button_pressed()) {
			change_freq();
		}

		// toggle led when systick counter is 0
		if (count_zero()) {
			toggle_led();
		}

	}
}
