/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "stm32f411xe.h"
#include "adc.h"
#include "uart.h"

int raw_volume;

void print_volume(int volume_percent)
{
	char msg[50];

	memset(msg, 0, sizeof(msg));
	snprintf(msg, sizeof(msg), "< Current Volume : %d%% >\r\n", volume_percent);

	uart_write_str(msg);
}

int main(void)
{
	adc_en();
	uart_en();
	uart_write_str("< Start Volume Monitoring!! >\r\n");

	while(1) {
		raw_volume = adc_get();
		int vol_percent = (raw_volume * 100) / 4095;
		print_volume(vol_percent);

		for(volatile int i = 0; i < 2000000; i++);
	}

}
