/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"

#include "gpio.h"

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{

	uint32_t led_pin = led_en();
	uint32_t button = button_en();

	// button is active LOW, not active HIGH!
	while(1) {
		// if bit is high (button not pressed)
		if (GPIOC->IDR & button) {
			GPIOA->ODR &= ~led_pin;
		} else {
			GPIOA->ODR |= led_pin;
		}
	}
}
