/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"


volatile uint32_t p1 = 0, p2 = 0, pulse_width = 0;
volatile float distance = 0;


void delay_us(uint16_t us) {
	TIM1->CNT = 0;
	while (TIM1->CNT < us);
}


int main(void)
{
	// allow floating point math
	SCB->CPACR |= ( (3UL << 10 * 2) | (3UL << 11 * 2) );


	//_________LED PIN__________

	// RCC->AHB1ENR corresponds to offset 0x30 from RCC base
	// activate GPIOB clock
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

	// MODE0 to general purpose output mode
	// num << shift_amount
	GPIOB->MODER &= ~(3 << 0);	// 3 (11) << 0 results in 11, so inverse is 00
	GPIOB->MODER |= (1 << 0);	// 00 to 01


	//_________ULTRASONIC SENSOR__________

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;	// enable clock for PA9 standard output
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;

	// set PA9 to output mode
	GPIOA->MODER &= ~(3 << (9 * 2));
	GPIOA->MODER |= (1 << (9 * 2));

	// set PA8 to alternate mode
	GPIOA->MODER &= ~(3 << (8 * 2));
	GPIOA->MODER |= (2 << (8 * 2));
	GPIOA->AFR[1] &= ~(0xF << 0);
	GPIOA->AFR[1] |= (1 << 0);




	// set from 100MHz clk to 1MHz, allows for timer to tick every 1us (1/1M = 1u)
	TIM1->PSC = 99;
	TIM1->ARR = 0xFFFF;

	// configure capture/compare mode register 1, channel 1 as input for TI1
	TIM1->CCMR1 &= ~TIM_CCMR1_CC1S;
	TIM1->CCMR1 |= 0x01;

	TIM1->CCER |= TIM_CCER_CC1E;	// enable capture for channel 1
	TIM1->CCER &= ~(TIM_CCER_CC1P | TIM_CCER_CC1NP);	// set output polarity to rising edge

	TIM1->CR1 |= TIM_CR1_CEN; // counter enabled, start timer

	while (1) {

		// 10us trigger pulse
		GPIOA->ODR |= (1<<9);	// turn on PA9
		delay_us(10);
		GPIOA->ODR &= ~(1<<9);	// turn off PA9

		// wait to capture rising edge
		// must disable capture channel before changing polarity bits
		TIM1->CCER &= ~TIM_CCER_CC1E;
		TIM1->CCER &= ~(TIM_CCER_CC1P | TIM_CCER_CC1NP);
		TIM1->CCER |= TIM_CCER_CC1E;

		TIM1->SR &= ~TIM_SR_CC1IF;	// clear flag
		while( !(TIM1->SR & TIM_SR_CC1IF) );   // blocking wait
		p1 = TIM1->CCR1;	// capture time of high right after rising edge

		// wait to capture falling edge

		TIM1->CCER &= ~TIM_CCER_CC1E;
		TIM1->CCER |= TIM_CCER_CC1P;	// set to 1
		TIM1->CCER |= TIM_CCER_CC1E;

		TIM1->SR &= ~TIM_SR_CC1IF;	// clear flag
		while( !(TIM1->SR & TIM_SR_CC1IF) );
		p2 = TIM1->CCR1;	// capture time at falling edge

		if (p2 > p1)
			pulse_width = p2 - p1;
		else
			// handle overflow, invert p1
			pulse_width = (0xFFFF - p1) + p2;

		distance = pulse_width * 0.0343 /2;

		if (distance < 15.0) {
			GPIOB->ODR |= (1 << 0); // LED on
		} else {
			GPIOB->ODR &= ~(1 << 0); // LED off
		}

		delay_us(50000);
	}
}
